version: '3'

services:
  redis:
    image: redis:7.2-alpine3.18
    container_name: redis-srv
    ports:
      - 6379:6379
    restart: unless-stopped

  consumer_one:
    container_name: go-consumer-one
    build:
      dockerfile: ./Dockerfile.consumer
      context: .
    environment:
      APP_ENV: docker
      APP_VERSION: 1.0.0
      LOG_LEVEL: debug
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CONSUMER_GROUP: consumer-group-one
    depends_on:
      - redis
    restart: unless-stopped

  consumer_two:
    container_name: go-consumer-two
    build:
      dockerfile: ./Dockerfile.consumer
      context: .
    environment:
      APP_ENV: docker
      APP_VERSION: 1.0.0
      LOG_LEVEL: debug
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CONSUMER_GROUP: consumer-group-one
    depends_on:
      - redis
    restart: unless-stopped

  consumer_three:
    container_name: go-consumer-three
    build:
      dockerfile: ./Dockerfile.consumer
      context: .
    environment:
      APP_ENV: docker
      APP_VERSION: 1.0.0
      LOG_LEVEL: debug
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CONSUMER_GROUP: consumer-group-two
    depends_on:
      - redis
    restart: unless-stopped

  consumer_four:
    container_name: go-consumer-four
    build:
      dockerfile: ./Dockerfile.consumer
      context: .
    environment:
      APP_ENV: docker
      APP_VERSION: 1.0.0
      LOG_LEVEL: debug
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CONSUMER_GROUP: consumer-group-two
    depends_on:
      - redis
    restart: unless-stopped

  publisher_one:
    container_name: go-publisher-one
    build:
      dockerfile: ./Dockerfile.publisher
      context: .
    environment:
      APP_ENV: docker
      APP_VERSION: 1.0.0
      LOG_LEVEL: debug
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - consumer_one
      - consumer_two
      - consumer_three
      - consumer_four
    restart: no

  publisher_two:
    container_name: go-publisher-two
    build:
      dockerfile: ./Dockerfile.publisher
      context: .
    environment:
      APP_ENV: docker
      APP_VERSION: 1.0.0
      LOG_LEVEL: debug
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - publisher_one
    restart: no
